sudo: false

before_install: umask 0022

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
  - 2.11.12

script:
  - cd play-2.4/swagger-play2 && sbt ++$TRAVIS_SCALA_VERSION compile test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - cd ../..
  - cd play-2.5/swagger-play2 && sbt ++$TRAVIS_SCALA_VERSION compile test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - cd ../..
  - cd play-2.6/swagger-play2 && sbt ++$TRAVIS_SCALA_VERSION compile test
  - find $HOME/.sbt -name "*.lock" | xargs rm

jdk:
  - openjdk8
